name: bru_linter_dart
description: A starting point for Dart libraries or applications.
version: 1.0.1

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  analyzer:
  analyzer_plugin:
  custom_lint_builder:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
